/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./services.html",
    "./about.html",
    "./blog.html",
    "./contact.html",
    "./src/**/*.{js,ts,jsx,tsx,css}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface": "#121416",
        "surface-container-highest": "#333537",
        "surface-bright": "#37393b",
        "on-tertiary-fixed-variant": "#41474f",
        "outline": "#909098",
        "on-tertiary-fixed": "#161c23",
        "primary-fixed-dim": "#bcc5e9",
        "inverse-on-surface": "#2f3133",
        "tertiary-container": "#343b42",
        "secondary-container": "#835c00",
        "secondary": "#f1bf62",
        "surface-variant": "#333537",
        "on-surface-variant": "#c6c6ce",
        "secondary-fixed": "#ffdea8",
        "primary-fixed": "#dae1ff",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#101a36",
        "surface-container-high": "#282a2c",
        "surface-container-low": "#1a1c1e",
        "on-secondary-container": "#ffdba0",
        "background": "#121416",
        "on-primary-fixed-variant": "#3c4664",
        "on-error": "#690005",
        "on-surface": "#e2e2e5",
        "error": "#ffb4ab",
        "on-primary": "#252f4c",
        "surface-dim": "#121416",
        "on-secondary-fixed-variant": "#5e4200",
        "tertiary": "#c1c7d0",
        "error-container": "#93000a",
        "primary": "#bcc5e9",
        "primary-container": "#2f3956",
        "surface-tint": "#bcc5e9",
        "surface-container-lowest": "#0c0e10",
        "tertiary-fixed-dim": "#c1c7d0",
        "secondary-fixed-dim": "#f1bf62",
        "inverse-surface": "#e2e2e5",
        "outline-variant": "#45464d",
        "on-primary-container": "#99a3c5",
        "on-tertiary-container": "#9ea5ad",
        "on-secondary-fixed": "#271900",
        "surface-container": "#1e2022",
        "inverse-primary": "#545e7d",
        "on-secondary": "#422d00",
        "on-tertiary": "#2b3138",
        "tertiary-fixed": "#dde3ec",
        "on-background": "#e2e2e5"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "stitch-full": "0.75rem"
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Inter", "Noto Sans Georgian", "sans-serif"],
        label: ["Inter", "Noto Sans Georgian", "sans-serif"]
      }
    },
  },
  plugins: [],
}
