// IDC Centralized Booking & Products Catalog
export const BOOKING_SERVICES = [
  // --- ფსიქოთერაპიული სერვისები (Therapy & Coaching) ---
  {
    id: "consultation",
    slugs: ["consultation", "service-consultation", "კონსულტაცია"],
    category: "therapy",
    categoryLabel: "ფსიქოლოგიური სერვისი",
    name: "პირველადი კონსულტაცია",
    subtitle: "შეფასება & დიაგნოსტიკა",
    price: 100,
    priceFormatted: "100 ₾",
    duration: "50 წუთი",
    format: "პირისპირ (ჭავჭავაძის 2) ან ონლაინ (Meet/Zoom)",
    dateType: "calendar",
    description: "50-წუთიანი ინდივიდუალური სესია გამოცდილ ფსიქოთერაპევტთან. მდგომარეობის დეტალური შეფასება და შემდგომი თერაპიული ნაბიჯების დაგეგმვა.",
    icon: "support_agent",
    badge: "პირისპირ / ონლაინ",
    popular: true
  },
  {
    id: "individual-therapy",
    slugs: ["individual", "individual-therapy", "service-individual", "ინდივიდუალური-თერაპია"],
    category: "therapy",
    categoryLabel: "ფსიქოლოგიური სერვისი",
    name: "ინდივიდუალური ფსიქოთერაპია",
    subtitle: "პერსონალური 1-on-1 მუშაობა",
    price: 150,
    priceFormatted: "150 ₾",
    duration: "50-60 წუთი",
    format: "პირისპირ (ჭავჭავაძის 2) ან ონლაინ",
    dateType: "calendar",
    description: "სიღრმისეული ინდივიდუალური მუშაობა შფოთვის, დეპრესიის, ემოციური კრიზისის და თვითშეფასების საკითხებზე პოზიტიური ფსიქოთერაპიის მეთოდით.",
    icon: "person",
    badge: "1-on-1 თერაპია",
    popular: true
  },
  {
    id: "couples-therapy",
    slugs: ["couples", "couples-therapy", "წყვილთა-თერაპია"],
    category: "therapy",
    categoryLabel: "ფსიქოლოგიური სერვისი",
    name: "წყვილთა & ოჯახური თერაპია",
    subtitle: "ურთიერთობების ჰარმონიზაცია",
    price: 220,
    priceFormatted: "220 ₾",
    duration: "80-90 წუთი",
    format: "პირისპირ (ჭავჭავაძის 2) ან ონლაინ",
    dateType: "calendar",
    description: "კომუნიკაციის გაუმჯობესება, კონფლიქტების კონსტრუქციული გადაჭრა და ემოციური სიახლოვის აღდგენა ოჯახსა და წყვილში.",
    icon: "favorite",
    badge: "წყვილები & ოჯახი",
    popular: false
  },
  {
    id: "group-therapy",
    slugs: ["group", "group-therapy", "service-group", "ჯგუფური-თერაპია"],
    category: "therapy",
    categoryLabel: "ფსიქოლოგიური სერვისი",
    name: "ჯგუფური ფსიქოთერაპია",
    subtitle: "ურთიერთდახმარების & მხარდაჭერის ჯგუფი",
    price: 80,
    priceFormatted: "80 ₾ / სესია",
    duration: "120 წუთი (2 საათი)",
    format: "პირისპირ ჯგუფი (ჭავჭავაძის 2)",
    dateType: "calendar",
    description: "გამოცდილების გაზიარება და ურთიერთმხარდაჭერა უსაფრთხო, პროფესიონალურად მართულ ჯგუფურ გარემოში.",
    icon: "groups",
    badge: "მცირე ჯგუფი (8-10 კაცი)",
    popular: false
  },
  {
    id: "coaching",
    slugs: ["coaching", "service-coaching", "ქოუჩინგი"],
    category: "therapy",
    categoryLabel: "ფსიქოლოგიური სერვისი",
    name: "პერსონალური ქოუჩინგი",
    subtitle: "მიზნები, მოტივაცია & პიროვნული ზრდა",
    price: 160,
    priceFormatted: "160 ₾",
    duration: "60 წუთი",
    format: "პირისპირ ან ონლაინ",
    dateType: "calendar",
    description: "პროფესიული და პიროვნული მიზნების მკაფიო ფორმულირება, შინაგანი ბარიერების დაძლევა და ეფექტური სამოქმედო სტრატეგიის შემუშავება.",
    icon: "trending_up",
    badge: "ICF სტანდარტი",
    popular: false
  },
  {
    id: "group-coaching",
    slugs: ["group-coaching", "service-group-coaching", "ჯგუფური-ქოუჩინგი"],
    category: "therapy",
    categoryLabel: "ფსიქოლოგიური სერვისი",
    name: "ჯგუფური & კორპორატიული ქოუჩინგი",
    subtitle: "გუნდური ეფექტურობა & ლიდერობა",
    price: 350,
    priceFormatted: "350 ₾ / სესია",
    duration: "120 წუთი",
    format: "კორპორატიული / პირისპირ",
    dateType: "calendar",
    description: "გუნდური შეთანხმებულობა, კომუნიკაციური სინერგია და ლიდერული უნარების გაძლიერება ორგანიზაციებისთვის.",
    icon: "diversity_2",
    badge: "კორპორატიული",
    popular: false
  },

  // --- აკადემიური განათლება & კურსები (Education) ---
  {
    id: "wapp-basic",
    slugs: ["wapp", "wapp-basic", "education-wapp", "პოზიტიური-ფსიქოთერაპია"],
    category: "education",
    categoryLabel: "აკადემიური განათლება",
    name: "WAPP საერთაშორისო პროგრამა",
    subtitle: "პოზიტიური ფსიქოთერაპია — Basic Consultant",
    price: 2800,
    priceFormatted: "2,800 ₾",
    duration: "200 საათი (5 მოდული, 1 წელი)",
    format: "ჰიბრიდული (დასწრებული მოდულები + ონლაინ)",
    dateType: "cohort",
    nextStartDate: "15 ოქტომბერი 2026",
    schedule: "თვეში 1 შაბათ-კვირა: 10:00 — 18:00",
    description: "ვისბადენის აკადემიის (WAPP, Germany) აკრედიტირებული საერთაშორისო სასერტიფიკატო კურსი. უფლება იძლევა აწარმოოთ კონსულტირება პოზიტიური მიდგომით.",
    icon: "verified",
    badge: "WAPP & EAP ACCREDITED",
    popular: true
  },
  {
    id: "erickson-coaching",
    slugs: ["erickson", "erickson-coaching", "education-erickson", "ერიქსონის-აკადემია"],
    category: "education",
    categoryLabel: "აკადემიური განათლება",
    name: "ერიქსონის საერთაშორისო აკადემია",
    subtitle: "The Art & Science of Coaching (ICF)",
    price: 3200,
    priceFormatted: "3,200 ₾",
    duration: "4 მოდული (128 საათი)",
    format: "ინტენსიური ჰიბრიდული / ცოცხალი",
    dateType: "cohort",
    nextStartDate: "22 ოქტომბერი 2026",
    schedule: "4-დღიანი ინტენსიური მოდულები",
    description: "მსოფლიოში წამყვანი ქოუჩინგის პროგრამა ICF (International Coaching Federation) უმაღლესი აკრედიტაციით. საერთაშორისო სერტიფიკატი.",
    icon: "school",
    badge: "ICF GOLD STANDARD",
    popular: true
  },
  {
    id: "practical-psychology",
    slugs: ["practical", "practical-psychology", "education-practical", "პრაქტიკული-ფსიქოლოგია"],
    category: "education",
    categoryLabel: "აკადემიური განათლება",
    name: "პრაქტიკული ფსიქოლოგია & TOT",
    subtitle: "1-წლიანი ჰიბრიდული სასერტიფიკატო კურსი",
    price: 1900,
    priceFormatted: "1,900 ₾",
    duration: "1 წელი (180 საათი)",
    format: "ჰიბრიდული (თეორია ონლაინ + პრაქტიკა პირისპირ)",
    dateType: "cohort",
    nextStartDate: "1 ნოემბერი 2026",
    schedule: "კვირაში 2-ჯერ (საღამოს საათებში)",
    description: "საფუძვლიანი პრაქტიკული მომზადება: დიაგნოსტიკური ინსტრუმენტები, ფსიქოკონსულტირების ტექნიკები და ტრენერთა ტრენინგი (TOT).",
    icon: "psychology",
    badge: "ჰიბრიდული & TOT",
    popular: false
  },
  {
    id: "art-therapy",
    slugs: ["art", "art-therapy", "education-art", "არტთერაპია"],
    category: "education",
    categoryLabel: "აკადემიური განათლება",
    name: "არტთერაპიის 1-წლიანი კურსი",
    subtitle: "11 მიმართულება & კლინიკური პრაქტიკა",
    price: 2200,
    priceFormatted: "2,200 ₾",
    duration: "1 წელი (160 საათი)",
    format: "სტუდიური პრაქტიკა + თეორია",
    dateType: "cohort",
    nextStartDate: "10 ნოემბერი 2026",
    schedule: "შაბათობით: 11:00 — 16:00",
    description: "იზოთერაპია, ზღაპართერაპია, ქვიშის თერაპია, მუსიკათერაპია და მეტაფორული ბარათები. სიღრმისეული ექსპრესიული თერაპია.",
    icon: "palette",
    badge: "11 მიმართულება",
    popular: false
  },
  {
    id: "master-practitioner",
    slugs: ["master", "master-practitioner", "education-master", "სამაგისტრო-კურსი"],
    category: "education",
    categoryLabel: "აკადემიური განათლება",
    name: "WAPP სამაგისტრო კურსი",
    subtitle: "Master Course in Positive Psychotherapy",
    price: 3500,
    priceFormatted: "3,500 ₾",
    duration: "2 წელი (სუპერვიზია & კლინიკური პრაქტიკა)",
    format: "კლინიკური მოდულები + ევროპული სუპერვიზია",
    dateType: "cohort",
    nextStartDate: "15 ნოემბერი 2026",
    schedule: "ინტენსიური სასესიო გრაფიკი",
    description: "უმაღლესი დონის საერთაშორისო კვალიფიკაცია საბაზისო კურსის კურსდამთავრებულთათვის. ევროპული ფსიქოთერაპიული ლიცენზიის საფუძველი.",
    icon: "workspace_premium",
    badge: "MASTER LEVEL",
    popular: false
  },
  {
    id: "seminars-workshops",
    slugs: ["seminars", "seminars-workshops", "education-seminars", "სემინარები"],
    category: "education",
    categoryLabel: "აკადემიური განათლება",
    name: "სემინარები & ვორქშოფები",
    subtitle: "მოკლევადიანი ინტენსიური ტრენინგები",
    price: 250,
    priceFormatted: "250 ₾",
    duration: "1-2 დღიანი ინტენსივი (8-16 საათი)",
    format: "პირისპირ / ონლაინ ვორქშოფი",
    dateType: "cohort",
    nextStartDate: "25 ოქტომბერი 2026",
    schedule: "შაბათ-კვირა: 11:00 — 18:00",
    description: "თემატური მასტერკლასები და პრაქტიკული ვორქშოფები: სტრესის მართვა, ემოციური ინტელექტი, მშობლობა, წყვილის კრიზისები.",
    icon: "co_present",
    badge: "სერტიფიცირებული",
    popular: false
  }
];

export function findServiceByQuery(query) {
  if (!query) return BOOKING_SERVICES[0];
  const q = String(query).toLowerCase().trim();
  const found = BOOKING_SERVICES.find((s) =>
    s.id.toLowerCase() === q ||
    s.slugs.some((sl) => sl.toLowerCase() === q) ||
    s.name.toLowerCase().includes(q)
  );
  return found || BOOKING_SERVICES[0];
}
